name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  ci:
    strategy:
      matrix:
        go-version: ['1.15', '1.14', '1.13']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    name: ${{ matrix.os }}/${{ matrix.go-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
