name: CI
on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14', '1.13' ]
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2
      - name: actions/setup-go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: actions/cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: golangci/golangci-lint-action
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
