name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14', '1.13' ]
    name: Go ${{ matrix.go }} build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Setup golangci-lint
        run: >-
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
          sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINT_VERSION
        env:
          GOLANGCI_LINT_VERSION: v1.31.0
      - name: Cache modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup modules
        run: go mod download
      - name: Run golangci-lint
        run: golangci-lint run
      - name: Run tests
        run: go test -race -v ./...
